### PR TITLE
fix #2853 about replication rule link issue

### LINKED ISSUE #2853: replication rule  link does not work
v1.1.2-534-ga047c1f
in replication page, replication rule shown as a link,but does not work
repatag

### PR DESCRIPTION
**Pull request by pengpengshui**

### CODE REVIEW

File: src/ui_ng/src/app/replication/total-replication/total-replication-page.component.ts [hunk 1]
```diff
@@ -12,10 +12,20 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 import { Component } from '@angular/core';
+import {ReplicationRule} from "../../../../lib/src/service/interface";
```
Comment (steven-zou) [inline src/ui_ng/src/app/replication/total-replication/total-replication-page.component.ts]: Will not work at production mode

File: src/ui_ng/src/app/replication/total-replication/total-replication-page.component.ts [hunk 2]
```diff
@@ -12,10 +12,20 @@
...
   selector: 'total-replication',
   templateUrl: 'total-replication-page.component.html'
 })
 export class TotalReplicationPageComponent {
+
+  rule: ReplicationRule[];
+  constructor(private router: Router){}
+  customRedirect(rule: ReplicationRule): void {
+    if (rule) {
+      this.router.navigateByUrl(`/harbor/projects/${rule.project_id}/replications`);
```
Comment (steven-zou) [inline src/ui_ng/src/app/replication/total-replication/total-replication-page.component.ts]: Suppose use navigate and 'relativeTo' attribute to do this
